[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prose"
version = "0.4.0"
description = "Pre-processing Reduction of Senses Engine"
authors = [
    {name = "E. Nyangau"}
]
requires-python = ">=3.9"
dependencies = [
    "spacy<3.8.0",
    "pydantic>=2.0.0",
    "nltk>=3.8.1"
]

[tool.setuptools.packages.find]
where = ["src"]